version: '2.3'

networks:
  dionaea_local:

services:

# Dionaea service
  dionaea:
    build: .
    container_name: dionaea
    stdin_open: true
    tty: true
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - dionaea_local
    ports:
     - "20:20"
     - "21:21"
     - "80:80"
     - "443:443"
     - "445:445"
    image: "dtagdevsec/dionaea:2204"
    read_only: true
    volumes:
     - /ctrl1/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
     - /ctrl1/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
     - /ctrl1/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
     - /ctrl1/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
     - /ctrl1/dionaea:/opt/dionaea/var/dionaea
     - /ctrl1/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
     - /ctrl1/dionaea/log:/opt/dionaea/var/log
     - /ctrl1/dionaea/rtp:/opt/dionaea/var/dionaea/rtp

